In [31]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine
import os

In [32]:

# Connect to your SQLite database
engine = create_engine("sqlite:///../data/db/bluestock_mf.db")

In [33]:
# Check your current working directory first
os.getcwd()

'C:\\Users\\GOPI\\Documents\\Mutual_Fund_Analytics\\notebooks'

In [34]:
# Read the cleaned CSV files and load the tables
# Main Tables

dim_fund = pd.read_csv("../data/processed/clean_fund_master.csv")
fact_nav = pd.read_csv("../data/processed/clean_nav.csv")
fact_transactions = pd.read_csv("../data/processed/clean_transactions.csv")
fact_performance = pd.read_csv("../data/processed/clean_performance.csv")

In [35]:
# Remaining cleaned datasets
import pandas as pd

fund_house = pd.read_csv("../data/processed/clean_aum_by_fund_house.csv")
monthly_sip = pd.read_csv("../data/processed/clean_monthly_sip_inflows.csv")
category = pd.read_csv("../data/processed/clean_category_inflows.csv")
industry = pd.read_csv("../data/processed/clean_industry_folio_count.csv")
holdings = pd.read_csv("../data/processed/clean_portfolio_holdings.csv")
benchmark = pd.read_csv("../data/processed/clean_benchmark_indices.csv")

In [36]:
print(fund_house.head())

print(fund_house.columns)

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168
Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='object')

In [37]:
print(fact_performance.columns.tolist())

['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade', 'anomaly_flag', 'expense_ratio_valid']

In [38]:
fact_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,...,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade,anomaly_flag,expense_ratio_valid
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,...,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate,False,True
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,...,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate,False,True
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,...,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High,False,True
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,...,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High,False,True
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,...,1.52,2.11,4.0,-2.30,24101,0.77,5,Low,False,True

In [44]:
# Create dim_date

dates = pd.to_datetime(fact_nav["date"])

dim_date = pd.DataFrame({
    "date": dates.dt.date,
    "year": dates.dt.year,
    "quarter": dates.dt.quarter,
    "month": dates.dt.month,
    "month_name": dates.dt.month_name()
})

dim_date = dim_date.drop_duplicates()
print(dim_date.head())
print(dim_date.shape)

         date  year  quarter  month month_name
0  2022-01-03  2022        1      1    January
1  2022-01-04  2022        1      1    January
2  2022-01-05  2022        1      1    January
3  2022-01-06  2022        1      1    January
4  2022-01-07  2022        1      1    January
(1150, 5)

In [40]:
fund_house.columns.tolist()

['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

In [41]:
fund_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [49]:
#  Load the data into tables

dim_fund.to_sql("dim_fund", engine, if_exists="append", index=False)

40

In [50]:
#  Load the  fact_nav data into tables

fact_nav.to_sql("fact_nav", engine, if_exists="append", index=False)

46000

In [51]:
#  Load the fact_transactions data into tables

fact_transactions.to_sql("fact_transactions", engine, if_exists="append", index=False)

32778

In [52]:
#  Load the fact_performance data into tables

fact_performance.to_sql("fact_performance", engine, if_exists="append", index=False)

40

In [4]:
db_path = "../data/db/bluestock_mf.db"

conn = sqlite3.connect(db_path)

print("Database Created Successfully")
print(os.path.exists(db_path))

conn.close()

Database Created Successfully
True